-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Mar 23, 2021 at 06:20 AM
-- Server version: 10.1.38-MariaDB
-- PHP Version: 7.4.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `restore_db`
--

--
-- Dumping data for table `yokart_sms_templates`
--

INSERT INTO `yokart_sms_templates` (`stpl_id`, `stpl_slug`, `stpl_name`, `stpl_body`, `stpl_default_body`, `stpl_replacements`, `stpl_priority`, `stpl_publish`, `stpl_updated_by_id`, `stpl_updated_at`) VALUES
(1, 'forgot_password', 'Forgot Password', 'Hello {name},\r\nIt seems that you have used the forgot password option at {websiteName}.\r\nVerification code to reset your password is {verificationCode}.', 'Hello {name},\r\nIt seems that you have used the forgot password option at {websiteName}.\r\nVerification code to reset your password is {verificationCode}.', '{\"{name}\":\"User Name\", \"{verificationCode}\":\"Verification Code\",\"{websiteName}\": \"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(2, 'make_payment', 'Make Payment', 'Hello {name}, \nPlease use OTP: {otp} to make the payment.', 'Hello {name}, \r\nPlease use OTP: {otp} to make the payment.', '{\"{name}\":\"User Name\", \"{otp}\":\"Otp\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(3, 'todo_reminder', 'Todo Reminder', 'Hello {name}\r\nThis is reminder for your task - {description}', 'Hello {name}\r\nThis is reminder for your task - {description}', '{\"{name}\":\"Admin Name\", \"{description}\":\"Description\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(4, 'verify_phone', 'Verify Phone', 'Hello {name}, \r\nPlease verify your account with the following code {verificationCode}', 'Hello {name}, \r\nPlease verify your account with the following code {verificationCode}', '{\"{name}\":\"Name\", \"{verificationCode}\":\"Verfication Code\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(5, 'failed_admin_login_attempt', 'Failed Admin Login Attempt', 'Hello {name}\r\nYou have multiple failed login attempts. Please try logging in after 15 minutes.', 'Hello {name}\r\nYou have multiple failed login attempts. Please try logging in after 15 minutes.', '{\"{name}\":\"Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(6, 'cod_payment_link', 'Cod Payment Link', 'Hello {name}\r\nPayment link for order #{orderNumber} with amount {orderAmount} on {websiteName} is {url}', 'Hello {name}\r\nPayment link for order #{orderNumber} with amount {orderAmount} on {websiteName} is {url}', '{\"{name}\":\"Name\", \"{orderNumber}\":\"Order Number\", \"{orderAmount}\":\"Order Amount\", \"{url}\":\"Payment Link\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(7, 'cod_verification', 'Cod Verification', 'Hello {name}\r\nVerification code to place order on {websiteName} is {verificationCode}', 'Hello {name}\r\nVerification code to place order on {websiteName} is {verificationCode}', '{\"{name}\":\"Buyer Name\", \"{websiteName}\":\"Website Name\", \"{verificationCode}\":\"Verification Code\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(8, 'blank_template', 'Blank Template', 'This is a test template for the SMS', 'This is a test template for the SMS', '', 'high', 1, 0, '0000-00-00 00:00:00'),
(9, 'signup_verification', 'Signup Verification', 'Hello {name},\r\nThank you for signing up with {websiteName}.\r\nPlease verify your account with the following code {verificationCode}', 'Hello {name},\r\nThank you for signing up with {websiteName}.\r\nPlease verify your account with the following code {verificationCode}', '{\"{name}\":\"Name\", \"{verificationCode}\":\"Verfication Code\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(10, 'admin_verify_phone', 'Admin Phone Verification', 'Hello {name},\r\nIt seems that you have changed your email at {websiteName}.\r\nPlease verify your email by clicking on the link {link}', 'Hello {name},\r\nIt seems that you have changed your email at {websiteName}.\r\nPlease verify your email by clicking on the link {link}', '{\"{name}\":\"Name\", \"{websiteName}\":\"Website Name\", \"{link}\":\"link\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(11, 'newsletter_subscription_success', 'Newsletter Subscribed', 'Hello {name}\r\nThank you for joining our mailing list.', 'Hello {name}\r\nThank you for joining our mailing list.', '{\"{name}\":\"Buyer Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(12, 'newsletter_subscription_ended', 'Newsletter Un-subscribed', 'Hello {name}\r\nYou are unsubscribed from our mailing list.', 'Hello {name}\r\nYou are unsubscribed from our mailing list.', '{\"{name}\":\"Buyer Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(13, 'share_and_earn', 'Share And Earn', 'Hello {referralUser}\r\n{buyerName} has invited you to {websiteName}. Join and earn exiting rewards.', 'Hello {referralUser}\r\n{buyerName} has invited you to {websiteName}. Join and earn exiting rewards.', '{\"{referralUser}\":\"Referral Name\", \"{buyerName}\":\"Buyer Name\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(14, 'update_phone_verify', 'Update Phone Verification', 'Hello {name},\r\nIt seems that you have updated your phone number at {websiteName}.\r\nVerify your phone with the following code {verificationCode}', 'Hello {name},\r\nIt seems that you have updated your phone number at {websiteName}.\r\nVerify your phone with the following code {verificationCode}', '{\"{name}\":\"Name\", \"{verificationCode}\":\"Verfication Code\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(15, 'order_confirmation', 'Order Confirmation', 'Hello {name}\r\nYour order #{number} with amount {amount} has been successfully placed on {websiteName}', 'Hello {name}\r\nYour order #{number} with amount {amount} has been successfully placed on {websiteName}', '{\"{name}\":\"Name\", \"{number}\":\"Order Number\", \"{amount}\":\"Order Amount\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(16, 'pickup_order_confirmation', 'Pickup Order Confirmation', 'Hello {name}\r\nYour pickup order #{number} with amount {amount} has been successfully placed on {websiteName}', 'Hello {name}\r\nYour pickup order #{number} with amount {amount} has been successfully placed on {websiteName}', '{\"{name}\":\"Name\", \"{number}\":\"Order Number\", \"{amount}\":\"Order Amount\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(17, 'physical_ready_for_shipping', 'Physical order ready for shipping', 'Hello {name}\r\nYour order #{number} with amount {amount} is ready to be shipped on {websiteName}', 'Hello {name}\r\nYour order #{number} with amount {amount} is ready to be shipped on {websiteName}', '{\"{name}\":\"Name\", \"{number}\":\"Order Number\", \"{amount}\":\"Order Amount\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(18, 'physical_order_shipped', 'Physical order shipped', 'Hello {name}\r\nYour order #{number} with amount {amount} is on it\'s way from {websiteName}', 'Hello {name}\r\nYour order #{number} with amount {amount} is on it\'s way from {websiteName}', '{\"{name}\":\"Name\", \"{number}\":\"Order Number\", \"{amount}\":\"Order Amount\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(19, 'physical_order_delivered', 'Physical order delivered', 'Hello {name}\r\nYour order #{number} with amount {amount} is delivered from {websiteName}', 'Hello {name}\r\nYour order #{number} with amount {amount} is delivered from {websiteName}', '{\"{name}\":\"Name\", \"{number}\":\"Order Number\", \"{amount}\":\"Order Amount\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(20, 'digital_ready_for_shipping', 'Digital ready for shipping', 'Hello {name}\r\nYour order #{number} with amount {amount} is processed on {websiteName}', 'Hello {name}\r\nYour order #{number} with amount {amount} is processed on {websiteName}', '{\"{name}\":\"Name\", \"{number}\":\"Order Number\", \"{amount}\":\"Order Amount\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(21, 'digital_order_shipped', 'Digital order shipped', 'Hello {name}\r\nYour order #{number} with amount {amount} is being prepared by {websiteName}', 'Hello {name}\r\nYour order #{number} with amount {amount} is being prepared by {websiteName}', '{\"{name}\":\"Name\", \"{number}\":\"Order Number\", \"{amount}\":\"Order Amount\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(22, 'digital_order_delivered', 'Digital order delivered', 'Hello {name}\r\nYour order #{number} with amount {amount} is ready for download on {websiteName}', 'Hello {name}\r\nYour order #{number} with amount {amount} is ready for download on {websiteName}', '{\"{name}\":\"Name\", \"{number}\":\"Order Number\", \"{amount}\":\"Order Amount\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(23, 'welcome', 'Welcome', 'Hello {name}\r\nWelcome to {websiteName}. Browse new products and avail exciting offers on {websiteUrl}', 'Hello {name}\r\nWelcome to {websiteName}. Browse new products and avail exciting offers on {websiteUrl}', '{\"{name}\":\"Name\", \"{websiteUrl}\":\"Website Url\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(24, 'suspicious_login_attempt', 'Suspicious Login Attempts', 'Hello {name}\r\nYou have multiple failed login attempts. Please try logging in after 15 minutes.', 'Hello {name}\r\nYou have multiple failed login attempts. Please try logging in after 15 minutes.', '{\"{name}\":\"Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(25, 'admin_forgot_password', 'Admin Forgot Password', 'Hello {name},\r\nIt seems that you have changed your password at {websiteName}.\r\nPlease reset your password by clicking on the link {link}', 'Hello {name},\r\nIt seems that you have changed your password at {websiteName}.\r\nPlease reset your password by clicking on the link {link}', '{\"{name}\":\"User Name\", \"{link}\":\"Verification link\",\"{websiteName}\": \"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(26, 'message_admin', 'Message To Admin', 'Hello {name}\r\nYou have a new message on {productName}', 'Hello {name}\r\nYou have a new message on {productName}', '{\"{name}\":\"Admin Name\",\"{productName}\": \"Product Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(27, 'message_buyer', 'Message To Buyer', 'Hello {name}\r\nYou have a new message on your query for {productName}', 'Hello {name}\r\nYou have a new message on your query for {productName}', '{\"{name}\":\"Buyer Name\",\"{productName}\": \"Product Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(28, 'digital_download', 'Digital Products Download', 'Hello {name}\r\nYour order #{number} with amount {amount} is ready for download on {websiteName}', 'Hello {name}\r\nYour order #{number} with amount {amount} is ready for download on {websiteName}', '{\"{name}\":\"Buyer Name\", \"{number}\":\"Order Number\", \"{amount}\":\"Order Amount\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(29, 'cancellation_request_buyer', 'Cancellation Request Placed', 'Hello {name}\r\nYour cancellation request #{requestId} has been successfully placed. Please check your account for more details.', 'Hello {name}\r\nYour cancellation request #{requestId} has been successfully placed. Please check your account for more details.', '{\"{name}\":\"Buyer Name\", \"{requestId}\":\"Request Id\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(30, 'cancellation_request_admin', 'Cancellation Requested!', 'Hello {adminName}\r\nA new cancellation request #{requestId} has been received by {buyerName} Please check your account for more details.', 'Hello {adminName}\r\nA new cancellation request #{requestId} has been received by {buyerName} Please check your account for more details.', '{\"{adminName}\":\"Admin Name\", \"{buyerName}\":\"Buyer Name\", \"{requestId}\":\"Request Id\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(31, 'return_request_buyer', 'Return Request Placed!', 'Hello {name}\r\nYour return request #{requestId} has been successfully placed. Please check your account for more details.', 'Hello {name}\r\nYour return request #{requestId} has been successfully placed. Please check your account for more details.', '{\"{name}\":\"Buyer Name\", \"{requestId}\":\"Request Id\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(32, 'return_request_admin', 'Return Requested!', 'Hello {adminName}\r\nA new return request #{requestId} has been received by {buyerName} Please check your account for more details.', 'Hello {adminName}\r\nA new return request #{requestId} has been received by {buyerName} Please check your account for more details.', '{\"{adminName}\":\"Admin Name\", \"{buyerName}\":\"Buyer Name\", \"{requestId}\":\"Request Id\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(33, 'return_declined', 'Return Declined!', 'Hello {name}\r\nYour return request #{requestId} has been declined. Please check your account for more details.', 'Hello {name}\r\nYour return request #{requestId} has been declined. Please check your account for more details.', '{\"{name}\":\"Buyer Name\", \"{requestId}\":\"Request Id\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(34, 'return_approved', 'Return Approved!', 'Hello {name}\r\nYour return request #{requestId} has been approved. Refund amount should reflect in the next 2-3 business days.', 'Hello {name}\r\nYour return request #{requestId} has been approved. Refund amount should reflect in the next 2-3 business days.', '{\"{name}\":\"Buyer Name\", \"{requestId}\":\"Request Id\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(35, 'gdpr_delete_account', 'GDPR Delete Account', 'Hello {name}\r\nYour request has been processed and account is deleted.', 'Hello {name}\r\nYour request has been processed and account is deleted.', '{\"{name}\":\"Buyer Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(36, 'comment_by_buyer_on_order', 'New comment posted by User on Order', 'Hello {name}\r\nYou have a new comment on your order #{orderNumber}', 'Hello {name}\r\nYou have a new comment on your order #{orderNumber}', '{\"{name}\":\"Admin Name\", \"{orderNumber}\":\"Order Number\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(37, 'comment_by_admin_on_order', 'New comment posted by Admin on Order', 'Hello {name}\r\nYou have a new comment on your order #{orderNumber}', 'Hello {name}\r\nYou have a new comment on your order #{orderNumber}', '{\"{name}\":\"Buyer Name\", \"{orderNumber}\":\"Order Number\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(38, 'low_stock_notification_for_product', 'Low stock notification for Product', 'Hello {name}\r\nAlert: Low inventory on {productName}', 'Hello {name}\r\nAlert: Low inventory on {productName}', '{\"{name}\":\"Admin Name\", \"{productName}\":\"{Product Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(39, 'new_order_notification_to_admin', 'New Order Notification To Admin', 'Hello {name}\r\nYou have a new order #{number} with amount {amount} from buyer {buyerName}', 'Hello {name}\r\nYou have a new order #{number} with amount {amount} from buyer {buyerName}', '{\"{name}\":\"Admin Name\", \"{number}\":\"Order Number\", \"{amount}\":\"Order Amount\", \"{buyerName}\":\"Buyer Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(40, 'payment_failed_new_link_for_buyer', 'Payment Failed New Payment link To Buyer', 'Hello {name}\r\nYour payment for order #{number} did not go through. Please log in to your account to update the payment details', 'Hello {name}\r\nYour payment for order #{number} did not go through. Please log in to your account to update the payment details', '{\"{name}\":\"Buyer Name\", \"{number}\":\"Order Number\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(41, 'todo_assigned', 'New Todo Assigned', 'Hello {toUserName}\r\n{fromUserName} has assigned a new to do on {websiteName}', 'Hello {toUserName}\r\n{fromUserName} has assigned a new to do on {websiteName}', '{\"{toUserName}\":\"To Admin Name\", \"{fromUserName}\":\"From Admin Name\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(42, 'pickup_order_packing', 'Pickup Order Packing', 'Hello {name}\r\nWe are packing your order #{number} with amount {amount} on {websiteName}', 'Hello {name}\r\nWe are packing your order #{number} with amount {amount} on {websiteName}', '{\"{name}\":\"Name\", \"{number}\":\"Order Number\", \"{amount}\":\"Order Amount\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(43, 'pickup_order_ready_for_pickup', 'Pickup Order Ready For Pickup', 'Hello {name}\r\nYour order #{number} with amount {amount} is ready for pickup on {websiteName}', 'Hello {name}\r\nYour order #{number} with amount {amount} is ready for pickup on {websiteName}', '{\"{name}\":\"Name\", \"{number}\":\"Order Number\", \"{amount}\":\"Order Amount\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00'),
(44, 'pickup_order_pickedup', 'Pickup Order Picked Up', 'Hello {name}\r\nYou have successfully picked up your order #{number} from {websiteName}', 'Hello {name}\r\nYou have successfully picked up your order #{number} from {websiteName}', '{\"{name}\":\"Name\", \"{number}\":\"Order Number\", \"{websiteName}\":\"Website Name\"}', 'high', 1, 0, '0000-00-00 00:00:00');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
