-- phpMyAdmin SQL Dump
-- version 4.6.6deb5ubuntu0.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Aug 17, 2021 at 01:15 PM
-- Server version: 5.7.35-0ubuntu0.18.04.1
-- PHP Version: 7.4.20

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `testingproject`
--

--
-- Dumping data for table `yokart_app_notification_templates`
--

INSERT INTO `yokart_app_notification_templates` (`antpl_id`, `antpl_slug`, `antpl_name`, `antpl_body`, `antpl_default_body`, `antpl_replacements`, `antpl_priority`, `antpl_publish`, `antpl_updated_by_id`, `antpl_updated_at`, `antpl_title`) VALUES
(1, 'cod_verification', 'Cod Verification', 'Verification code to place Order is {verification_code}', 'Verification code to place Order is {verification_code}', '{\"{User}\":\"User Name\", \"{Order_id}\":\"Order ID\", \"{Website_name}\":\"Website Name\", \"{Verification_Code}\":\"Verification Code\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Verification code for your cash on delivery order on {website_name}'),
(2, 'cod_payment_link', 'Cod Payment Link', 'Payment link for Order# {order_id} with amount {order_amount} \r\n is {link}', 'Payment link for Order# {order_id} with amount {order_amount} \r\n is {link}', '{\"{User}\":\"User Name\", \"{Order_id}\":\"Order ID\", \"{currency}\":\"Currency\", \"{order_amount}\":\"Order Amount\", \"{website_name}\":\"Website Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Cod Payment Link'),
(3, 'order_confirmation', 'Order Confirmation', 'Your order# {order_number} with amount {order_amount} has been successfully placed.', 'Your order# {order_number} with amount {order_amount} has been successfully placed.', '{\"{User}\":\"User Name\", \"{order_number}\":\"Order Number\", \"{currency}\":\"Currency\", \"{order_amount}\":\"Order Amount\", \"{website_name}\":\"Website Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Your order {order_number} on {website_name}'),
(4, 'physical_ready_for_shipping', 'Physical order ready for shipping', 'Your order# {order_number} with amount {order_amount} is ready to be shipped', 'Your order# {order_number} with amount {order_amount} is ready to be shipped', '{\"{User}\":\"User Name\", \"{order_number}\":\"Order Number\", \"{currency}\":\"Currency\", \"{order_amount}\":\"Order Amount\", \"{website_name}\":\"Website Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Order #{order_number} is ready to be shipped'),
(5, 'physical_order_shipped', 'Physical order shipped', 'Your order# {order_number} with amount {order_amount} is on it\'s way', 'Your order# {order_number} with amount {order_amount} is on it\'s way', '{\"{User}\":\"User Name\", \"{order_number}\":\"Order Number\", \"{currency}\":\"Currency\", \"{order_amount}\":\"Order Amount\", \"{website_name}\":\"Website Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Order #{order_number} is on its way'),
(6, 'physical_order_delivered', 'Physical order delivered', 'Your order# {order_number} with amount {order_amount} is delivered', 'Your order# {order_number} with amount {order_amount} is delivered', '{\"{User}\":\"User Name\", \"{order_number}\":\"Order Number\", \"{currency}\":\"Currency\", \"{order_amount}\":\"Order Amount\", \"{website_name}\":\"Website Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Order #{order_number} is delivered'),
(7, 'digital_ready_for_shipping', 'Digital ready for shipping', 'Your order# {order_number} with amount {order_amount} is being prepared', 'Your order# {order_number} with amount {order_amount} is being prepared', '{\"{User}\":\"User Name\", \"{order_number}\":\"Order Number\", \"{currency}\":\"Currency\", \"{order_amount}\":\"Order Amount\", \"{website_name}\":\"Website Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'We\'re generating links for your Order # {order_number}'),
(8, 'digital_order_delivered', 'Digital order delivered', 'Your order# {order_number} with amount {order_amount} is ready for download', 'Your order# {order_number} with amount {order_amount} is ready for download', '{\"{User}\":\"User Name\", \"{order_number}\":\"Order Number\", \"{currency}\":\"Currency\", \"{order_amount}\":\"Order Amount\", \"{website_name}\":\"Website Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Order #{order_number} is ready for download'),
(9, 'digital_order_shipped', 'Digital order shipped', 'Your order# {order_number} with amount {order_amount} is in process', 'Your order# {order_number} with amount {order_amount} is in process', '{\"{User}\":\"User Name\", \"{order_number}\":\"Order Number\", \"{currency}\":\"Currency\", \"{order_amount}\":\"Order Amount\", \"{website_name}\":\"Website Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'We\'re working on you Order #{order_number}'),
(10, 'pickup_order_confirmation', 'Pickup order confirmation', 'Your pickup order# {order_number} with amount {order_amount} has been successfully placed.', 'Your pickup order# {order_number} with amount {order_amount} has been successfully placed.', '{\"{User}\":\"User Name\", \"{order_number}\":\"Order Number\", \"{currency}\":\"Currency\", \"{order_amount}\":\"Order Amount\", \"{website_name}\":\"Website Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Pickup order #{order_number} on {website_name}'),
(11, 'welcome', 'Welcome', 'Hello {User}\r\nWelcome to {website_name}. Browse new products and avail exciting offers on {website_url}', 'Hello {User}\r\nWelcome to {website_name}. Browse new products and avail exciting offers on {website_url}', '{\"{User}\":\"User Name\", \"{website_name}\":\"Website Name\"}, \"{website_url}\":\"Website Url\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Welcome to {website_name}'),
(12, 'rewards_earned_on_birthday', 'Rewards Earned on Birthday', 'Happy birthday and here\'s wishing you a fantastic year ahead. To make your birthday even more special we\'ve added {reward_points} points to your account.', 'Happy birthday and here\'s wishing you a fantastic year ahead. To make your birthday even more special we\'ve added {reward_points} points to your account.', '{\"{User}\":\"User Name\", \"{reward_points}\":\"Reward Points\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'A special gift from us on your Birthday!'),
(13, 'rewards_earned_on_social_sharing', 'Rewards Earned on Social Sharing', 'We like to reward our well wishers! For spreading the word around we\'ve added {reward_points} points to your account.', 'We like to reward our well wishers! For spreading the word around we\'ve added {reward_points} points to your account.', '{\"{User}\":\"User Name\", \"{reward_points}\":\"Reward Points\"}', 'normal', 1, 1, '2021-08-09 07:09:49', '{reward_points} reward points credited to your account for getting your friends onboard!'),
(14, 'rewards_expired', 'Rewards Expired', '{reward_points} points are about to expire in your account.   \r\nOrder now before its too late!', '{reward_points} points are about to expire in your account.   \r\nOrder now before its too late!', '{\"{User}\":\"User Name\", \"{reward_points}\":\"Reward Points\"}', 'normal', 1, 1, '2021-08-09 07:09:49', '{reward_points} reward points expired from your account'),
(15, 'rewards_earned_on_order', 'Rewards Earned on Order', 'Thank you for buying from us. For order {order_id} we\'ve added {reward_points} points to your account.', 'Thank you for buying from us. For order {order_id} we\'ve added {reward_points} points to your account.', '{\"{User}\":\"User Name\", \"{order_id}\":\"Order ID\", \"{reward_points}\":\"Reward Points\"}', 'normal', 1, 1, '2021-08-09 07:09:49', '{reward_points} reward points credited to your account for Order # {order_number}'),
(16, 'rewards_spent_on_order', 'Rewards Spent on Order', 'Thank you for buying from us. For order {order_id} you\'ve used {reward_points} points from your account.', 'Thank you for buying from us. For order {order_id} you\'ve used {reward_points} points from your account.', '{\"{User}\":\"User Name\", \"{order_id}\":\"Order ID\", \"{reward_points}\":\"Reward Points\"}', 'normal', 1, 1, '2021-08-09 07:09:49', '{reward_points} reward points used towards Order # {order_number}'),
(17, 'buyer_give_review', 'Buyer give review', 'Hello {User}\r\nThank you for buying from us. We would love to hear how we did. Please review us for your recent order with us.', 'Hello {User}\r\nThank you for buying from us. We would love to hear how we did. Please review us for your recent order with us. ', '{\"{User}\":\"User Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'We\'d love to hear from you on how we did!'),
(18, 'buyer_message', 'Buyer message', 'You have a new message on your query for {product_name}', 'You have a new message on your query for {product_name} ', '{\"{User}\":\"User Name\",\"{product_name}\":\"Product Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'New message on {website_name} for product - {product_name}'),
(19, 'digital_products_download', 'Digital Products Download', 'Your order# {order_number} with amount {order_amount} is ready for download', 'Your order# {order_number} with amount {order_amount} is ready for download', '{\"{User}\":\"User Name\",\"{order_number}\":\"Order Number\", \"{currency}\":\"Currency\", \"{website_name}\":\"Website Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Order # {order_number} - Your download link is ready.'),
(20, 'cancellation_request_placed', 'Cancellation Request Placed', 'Hello {User}\r\nYour cancellation request# {request_id} has been successfully placed. Please check your account for more details.', 'Hello {User}\r\nYour cancellation request# {request_id} has been successfully placed. Please check your account for more details. ', '{\"{User}\":\"User Name\",\"{request_id}\":\"Request ID\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Cancellation requested for Order # {order_number}'),
(21, 'cancellation_requested', 'Cancellation Requested!', 'Hello {User}\r\nA new cancellation request# {request_id} has been received by {buyer_name} Please check your account for more details.', 'Hello {User}\r\nA new cancellation request# {request_id} has been received by {buyer_name} Please check your account for more details.', '{\"{User}\":\"User Name\", \"{request_id}\":\"Request ID\", \"{buyer_name}\":\"Buyer Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Cancellation request {request_id} for Order # {order_number}'),
(22, 'return_request_placed', 'Return Request Placed!', 'Hello {User}\r\nYour return request# {request_id} has been successfully placed. Please check your account for more details.', 'Hello {User}\r\nYour return request# {request_id} has been successfully placed. Please check your account for more details.', '{\"{User}\":\"User Name\", \"{request_id}\":\"Request ID\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Return request {request_id} submitted for Order # {order_number}'),
(23, 'return_requested', 'Return Requested!', 'Hello {User}\r\nA new return request# {request_id} has been received by {buyer_name} Please check your account for more details.', 'Hello {User}\r\nA new return request# {request_id} has been received by {buyer_name} Please check your account for more details.', '{\"{User}\":\"User Name\", \"{request_id}\":\"Request ID\", \"{buyer_name}\":\"Buyer Name\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Return requested by {buyer_name} on Order # {order_number}'),
(24, 'return_declined', 'Return Declined!', 'Your return request# {request_id} has been declined. Please check your account for more details.', 'Your return request# {request_id} has been declined. Please check your account for more details.', '{\"{User}\":\"User Name\", \"{request_id}\":\"Request ID\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Return Declined!'),
(25, 'return_approved', 'Return Approved!', 'Your return request# {request_id} has been approved. Refund amount should reflect in the next 2-3 business days.', 'Your return request# {request_id} has been approved. Refund amount should reflect in the next 2-3 business days.', '{\"{User}\":\"User Name\", \"{request_id}\":\"Request ID\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Return Approved!'),
(26, 'new_comment_posted_by_admin_on_order', 'New comment posted by Admin on Order', 'You have a new comment on your order#{order_id}', 'You have a new comment on your order#{order_id}', '{\"{order_id}\":\"Order ID\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'New comment posted by {adminName} on Order# {order_number}'),
(27, 'payment_failed_new_payment_link_to_buyer', 'Payment Failed New Payment link To Buyer', 'Your payment for Order# {order_numer} did not go through. Please log in to your account to update the payment details', 'Your payment for Order# {order_numer} did not go through. Please log in to your account to update the payment details', '{\"{order_numer}\":\"Order Number\"}', 'normal', 1, 1, '2021-08-09 07:09:49', 'Payment failed for order {order_number} on {website_name}');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
